/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastIndexRouteImport } from './routes/$podcast.index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as PodcastLatestIndexRouteImport } from './routes/$podcast.latest.index'
import { Route as PodcastEpisodesIndexRouteImport } from './routes/$podcast.episodes.index'
import { Route as PodcastEpisodesIdIndexRouteImport } from './routes/$podcast.episodes.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/$podcast/',
  path: '/$podcast/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastLatestIndexRoute = PodcastLatestIndexRouteImport.update({
  id: '/$podcast/latest/',
  path: '/$podcast/latest/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastEpisodesIndexRoute = PodcastEpisodesIndexRouteImport.update({
  id: '/$podcast/episodes/',
  path: '/$podcast/episodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastEpisodesIdIndexRoute = PodcastEpisodesIdIndexRouteImport.update({
  id: '/$podcast/episodes/$id/',
  path: '/$podcast/episodes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/$podcast': typeof PodcastIndexRoute
  '/$podcast/episodes': typeof PodcastEpisodesIndexRoute
  '/$podcast/latest': typeof PodcastLatestIndexRoute
  '/$podcast/episodes/$id': typeof PodcastEpisodesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/$podcast': typeof PodcastIndexRoute
  '/$podcast/episodes': typeof PodcastEpisodesIndexRoute
  '/$podcast/latest': typeof PodcastLatestIndexRoute
  '/$podcast/episodes/$id': typeof PodcastEpisodesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/$podcast/': typeof PodcastIndexRoute
  '/$podcast/episodes/': typeof PodcastEpisodesIndexRoute
  '/$podcast/latest/': typeof PodcastLatestIndexRoute
  '/$podcast/episodes/$id/': typeof PodcastEpisodesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/$podcast'
    | '/$podcast/episodes'
    | '/$podcast/latest'
    | '/$podcast/episodes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/$podcast'
    | '/$podcast/episodes'
    | '/$podcast/latest'
    | '/$podcast/episodes/$id'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/$podcast/'
    | '/$podcast/episodes/'
    | '/$podcast/latest/'
    | '/$podcast/episodes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  PodcastIndexRoute: typeof PodcastIndexRoute
  PodcastEpisodesIndexRoute: typeof PodcastEpisodesIndexRoute
  PodcastLatestIndexRoute: typeof PodcastLatestIndexRoute
  PodcastEpisodesIdIndexRoute: typeof PodcastEpisodesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$podcast/': {
      id: '/$podcast/'
      path: '/$podcast'
      fullPath: '/$podcast'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$podcast/latest/': {
      id: '/$podcast/latest/'
      path: '/$podcast/latest'
      fullPath: '/$podcast/latest'
      preLoaderRoute: typeof PodcastLatestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$podcast/episodes/': {
      id: '/$podcast/episodes/'
      path: '/$podcast/episodes'
      fullPath: '/$podcast/episodes'
      preLoaderRoute: typeof PodcastEpisodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$podcast/episodes/$id/': {
      id: '/$podcast/episodes/$id/'
      path: '/$podcast/episodes/$id'
      fullPath: '/$podcast/episodes/$id'
      preLoaderRoute: typeof PodcastEpisodesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  PodcastIndexRoute: PodcastIndexRoute,
  PodcastEpisodesIndexRoute: PodcastEpisodesIndexRoute,
  PodcastLatestIndexRoute: PodcastLatestIndexRoute,
  PodcastEpisodesIdIndexRoute: PodcastEpisodesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
